# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d94df3000b26c3de9fbf5f955de6a264f7f6552942ca22031ac984b7a91d059b348009d32a7279bc00882ab7401ceeee719edc7824232ef7d648867ee54a828

test:
  secret_key_base: f0a26d1a233d406d44818e5a663944c09a33a6f69cdb10dccef4d7287f40b357673b841593147b13f671b08b4e9f990d7e2d78f49d2aa249eb8278d8ab184018

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
